---
abstract: 'Документация Perl по-русски'
author:
  - 'Команда Perl по-русски, Moscow-pm'
build_requires: {}
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POD2-RU
provides:
  POD2::RU:
    file: lib/POD2/RU.pm
    version: v5.18.0.1.4
requires:
  POD2::Base: 0.043
  Pod::Perldoc: 3.15
  Test::More: 0
  Test::More::UTF8: 0.04
resources:
  license: http://dev.perl.org/licenses/
version: v5.18.0.1.4
